# No game data: explicit errors, library errors, unknown exceptions and fatal aborts.
foreach(mode explicit library unknown fatal)
  set(dir "${WORK}/${mode}")
  file(REMOVE_RECURSE "${dir}")
  file(MAKE_DIRECTORY "${dir}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E env "WWHD_TEST_RUNTIME_ERROR=${mode}"
                  WWHD_NO_AUDIO=1 WWHD_NO_HOST_INPUT=1 WWHD_LOG_FILE=0 "WWHD_USER_DIR=${dir}/user" "${WWHD}"
                  WORKING_DIRECTORY "${dir}" RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err TIMEOUT 30)
  if(rc EQUAL 0)
    message(FATAL_ERROR "${mode} did not terminate")
  endif()
  file(GLOB logs "${dir}/captures/crash-*.log")
  list(LENGTH logs count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "${mode}: expected one crash log, got ${count}: ${err}")
  endif()
  file(READ "${logs}" crash)
  file(READ "${dir}/captures/wwhd.log" regular)
  if(mode STREQUAL unknown)
    set(expected "native game callback: unknown C[+][+] exception")
  else()
    set(expected "synthetic ${mode} message")
  endif()
  foreach(log crash regular)
    if(NOT "${${log}}" MATCHES "${expected}")
      message(FATAL_ERROR "${mode}: ${log} lacks original error: ${${log}}")
    endif()
  endforeach()
  if(NOT crash MATCHES "Last reported runtime error on this thread")
    message(FATAL_ERROR "${mode}: missing preserved thread error")
  endif()
endforeach()
